# Generated by Django 5.1.3 on 2024-11-22 08:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "date_of_death",
                    models.DateField(blank=True, null=True, verbose_name="Died"),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="SongGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Enter the song genre", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "summary",
                    models.TextField(
                        help_text="Enter the song summary", max_length=1000
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.author",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        help_text="Select a song genre", to="catalog.songgenre"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SongInstance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("5e089e27-5214-453f-8da7-d9d635c1200a"),
                        help_text="Unique ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=100)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("c", "copyright"), ("n", "NOcopyright")],
                        default="c",
                        help_text="song copyright",
                        max_length=1,
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.song",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
