# Generated by Django 5.1.3 on 2024-11-22 08:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"ordering": ["name"]},
        ),
        migrations.RenameField(
            model_name="author",
            old_name="first_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="author",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="songinstance",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("95605b62-2874-495b-b836-4c0ec88cf499"),
                help_text="Unique ID",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
