# Generated by Django 5.1.3 on 2024-11-26 07:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_author_options_rename_first_name_author_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songinstance",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("ea388697-c9f9-4e92-b242-9931a2e7b0df"),
                help_text="Unique ID",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
