# Generated by Django 5.1.3 on 2024-11-26 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_songinstance_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songinstance",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c9d99594-ae66-4fb8-b764-3919f4e131ff"),
                help_text="Unique ID",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
