# Generated by Django 5.1.3 on 2024-11-26 07:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_songinstance_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songinstance",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("d181f834-ae2e-4320-86b6-aa48a36e21af"),
                help_text="Unique ID",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
