# Generated by Django 5.1.3 on 2025-03-10 06:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_songinstance_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='songinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('911f5a20-7746-48c4-8d35-a5942236f2bd'), help_text='Unique ID', primary_key=True, serialize=False),
        ),
    ]
