# Generated by Django 5.1.3 on 2025-04-14 11:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_song_file_alter_songinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4c4c50f7-4252-4e84-8f60-b88dce1097a0'), help_text='Unique ID', primary_key=True, serialize=False),
        ),
    ]
