# Generated by Django 5.1.3 on 2025-04-14 11:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_songinstance_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5c372b35-1cf2-4c86-a9ea-be183b8c57d2'), help_text='Unique ID', primary_key=True, serialize=False),
        ),
    ]
